### PR TITLE
Enable UseChecksum option pass-through

### PR DESCRIPTION
**Pull request by rastographics**
Allow user to pass in UseChecksum argument to the webdeploy command.
(false by default)

### CODE REVIEW

**Comment by rastographics** [comment]
My use case: I really need this to keep my vendor.js from updating every time and keeping my website users from getting cached version.

**Comment by davidebbo** [comment]
Thanks for your contribution! I pushed 1.7 to chocolatey (pending review).

**Comment by davidebbo** [comment]
Ok, it's up on there.

**Comment by rastographics** [comment]
awesome! thanks

**Pull request merged**
